remote_theme: wowthemesnet/mundana-theme-jekyll

# Site
name: 'David Suta'
title: 'David Suta'
description: 'David Suta page for resume and projects'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
disqus: 'david_suta'
email: 'jdsuta@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
sendgrid_list: 'https://cdn.forms-content.sg-form.com/c9076acb-743d-11ee-8598-c621d6c39121'

baseurl: ''
include: ["_pages"]
permalink: /:title/


# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  
authors:
    david:
      name:           David
      site:           https://jdsuta.github.io/
      avatar:         assets/images/David_Suta.jpg
      bio:            "I'm David – a curious engineer with a passion for all things tech-related! You'll often find me hitting the gym, spending time with my cat, and diving into the latest tech trends."
      email:          jdsuta@gmail.com
      twitter:        https://www.instagram.com/davidsvta/
      github:         https://github.com/jdsuta
      instagram:      https://www.instagram.com/davidsvta/
      linkedin:       https://www.linkedin.com/in/david-suta-588595a3/

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: David Suta
      avatar: assets/images/David_Suta.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
